#!/bin/bash
# This script runs the masked personas generation process

nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=raca --target_name=preta --unmarked_name=branca --text_col=substantive_list  --model_name=gemini-1.5-flash > personas/gemini-1.5-flash/substantive_list/preta_branca_substantive_list.txt 2>&1 &
nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=raca --target_name=parda --unmarked_name=branca --text_col=substantive_list  --model_name=gemini-1.5-flash > personas/gemini-1.5-flash/substantive_list/parda_branca_substantive_list.txt 2>&1 &
nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=raca --target_name=branca --unmarked_name=branca --text_col=substantive_list  --model_name=gemini-1.5-flash > personas/gemini-1.5-flash/substantive_list/branca_branca_substantive_list.txt 2>&1 &
nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=raca --target_name=amarela --unmarked_name=branca --text_col=substantive_list  --model_name=gemini-1.5-flash > personas/gemini-1.5-flash/substantive_list/amarela_branca_substantive_list.txt 2>&1 &
nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=raca --target_name=indígena --unmarked_name=branca --text_col=substantive_list  --model_name=gemini-1.5-flash > personas/gemini-1.5-flash/substantive_list/indígena_branca_substantive_list.txt 2>&1 &
nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=genero --target_name=homem --unmarked_name=homem --text_col=substantive_list  --model_name=gemini-1.5-flash > personas/gemini-1.5-flash/substantive_list/homem_homem_substantive_list.txt 2>&1 &
nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=genero --target_name=mulher --unmarked_name=homem --text_col=substantive_list  --model_name=gemini-1.5-flash > personas/gemini-1.5-flash/substantive_list/mulher_homem_substantive_list.txt 2>&1 &
nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=genero --target_name=não-binária --unmarked_name=homem --text_col=substantive_list  --model_name=gemini-1.5-flash > personas/gemini-1.5-flash/substantive_list/não-binária_homem_substantive_list.txt 2>&1 &
nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=regiao --target_name=nortista --unmarked_name=sudestina --text_col=substantive_list  --model_name=gemini-1.5-flash > personas/gemini-1.5-flash/substantive_list/nortista_sudestina_substantive_list.txt 2>&1 &
nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=regiao --target_name=nordestina --unmarked_name=sudestina --text_col=substantive_list  --model_name=gemini-1.5-flash > personas/gemini-1.5-flash/substantive_list/nordestina_sudestina_substantive_list.txt 2>&1 &
nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=regiao --target_name=sulista --unmarked_name=sudestina --text_col=substantive_list  --model_name=gemini-1.5-flash > personas/gemini-1.5-flash/substantive_list/sulista_sudestina_substantive_list.txt 2>&1 &
nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=regiao --target_name=sudestina --unmarked_name=sudestina --text_col=substantive_list  --model_name=gemini-1.5-flash > personas/gemini-1.5-flash/substantive_list/sudestina_sudestina_substantive_list.txt 2>&1 &
nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=regiao --target_name=centro-oestina --unmarked_name=sudestina --text_col=substantive_list  --model_name=gemini-1.5-flash > personas/gemini-1.5-flash/substantive_list/centro-oestina_sudestina_substantive_list.txt 2>&1 &
