#!/bin/bash
# This script runs the masked personas generation process

nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=raca --target_name=preta --unmarked_name=branca --text_col=response  --model_name=gemini-2.0-flash > personas/gemini-2.0-flash/response/preta_branca_response.txt 2>&1 &
nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=raca --target_name=parda --unmarked_name=branca --text_col=response  --model_name=gemini-2.0-flash > personas/gemini-2.0-flash/response/parda_branca_response.txt 2>&1 &
nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=raca --target_name=branca --unmarked_name=branca --text_col=response  --model_name=gemini-2.0-flash > personas/gemini-2.0-flash/response/branca_branca_response.txt 2>&1 &
nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=raca --target_name=amarela --unmarked_name=branca --text_col=response  --model_name=gemini-2.0-flash > personas/gemini-2.0-flash/response/amarela_branca_response.txt 2>&1 &
nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=raca --target_name=indígena --unmarked_name=branca --text_col=response  --model_name=gemini-2.0-flash > personas/gemini-2.0-flash/response/indígena_branca_response.txt 2>&1 &
nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=genero --target_name=homem --unmarked_name=homem --text_col=response  --model_name=gemini-2.0-flash > personas/gemini-2.0-flash/response/homem_homem_response.txt 2>&1 &
nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=genero --target_name=mulher --unmarked_name=homem --text_col=response  --model_name=gemini-2.0-flash > personas/gemini-2.0-flash/response/mulher_homem_response.txt 2>&1 &
nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=genero --target_name=não-binária --unmarked_name=homem --text_col=response  --model_name=gemini-2.0-flash > personas/gemini-2.0-flash/response/não-binária_homem_response.txt 2>&1 &
nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=regiao --target_name=nortista --unmarked_name=sudestina --text_col=response  --model_name=gemini-2.0-flash > personas/gemini-2.0-flash/response/nortista_sudestina_response.txt 2>&1 &
nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=regiao --target_name=nordestina --unmarked_name=sudestina --text_col=response  --model_name=gemini-2.0-flash > personas/gemini-2.0-flash/response/nordestina_sudestina_response.txt 2>&1 &
nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=regiao --target_name=sulista --unmarked_name=sudestina --text_col=response  --model_name=gemini-2.0-flash > personas/gemini-2.0-flash/response/sulista_sudestina_response.txt 2>&1 &
nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=regiao --target_name=sudestina --unmarked_name=sudestina --text_col=response  --model_name=gemini-2.0-flash > personas/gemini-2.0-flash/response/sudestina_sudestina_response.txt 2>&1 &
nohup python3 -u src/masked/masked_personas.py --input_file=data/merged_data.parquet --target_col=regiao --target_name=centro-oestina --unmarked_name=sudestina --text_col=response  --model_name=gemini-2.0-flash > personas/gemini-2.0-flash/response/centro-oestina_sudestina_response.txt 2>&1 &
